name: BuildCheck
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app
      - name: Build macOS
        run: set -o pipefail && xcodebuild -skipMacroValidation -scheme SwiftTextRenderer build -destination "generic/platform=macOS" | xcpretty
      - name: Build iOS
        run: set -o pipefail && xcodebuild -skipMacroValidation -scheme SwiftTextRenderer build -destination "generic/platform=iOS" | xcpretty
